"""add_carousel_gif_url

Revision ID: c9151b3120aa
Revises: 0001_initial_schema
Create Date: 2026-02-04 14:44:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9151b3120aa'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('carousel_gif_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'carousel_gif_url')
    # ### end Alembic commands ###
